apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config-files
data:
  string-literal.json: '{"a": "A", "b": "B", "c": {"nested": "C"}}'
  values.yaml: |
{{ .Values.config | toYaml | indent 4 }}
  values.json: |
    {{ .Values.config | toJson}}
