apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: kuard
    run: {{ .Release.Name }}
  name: {{ .Release.Name }}
spec:
  replicas: {{ .Values.podReplicas }}
  selector:
    matchLabels:
      run: {{ .Release.Name }}
  template:
    metadata:
      labels:
        run: {{ .Release.Name }}
    spec:
      volumes:
        - name: config-files
          configMap:
            name: {{ .Release.Name}}-config-files
      containers:
      - name: kuard
        image: gcr.io/kuar-demo/kuard-amd64:1
        volumeMounts:
        - name: config-files
          mountPath: /var/this-dir-doesnt-need-to-exist/files
